### ISSUE TITLE
Add Dotspatial Plugin

### ISSUE THREAD

**Issue by Squill3x** [Squill3x/xsealence#2]
# Feature Request

### Description:
Add Dotspatial plugin.

### Tasks:
- [ ] Add Dotspatial plugin module.
- [ ] Implement Dotspatial module GISEngineBase class.
- [ ] Implement Dotspatial module DocumentViewModel class.
