### ISSUE TITLE
Add GMaps Plugin

### ISSUE THREAD

**Issue by Squill3x** [Squill3x/xsealence#3]
# Feature Request

### Description:
Add GMaps plugin.

### Tasks:
- [ ] Add GMaps plugin module.
- [ ] Implement GMaps module GISEngineBase class.
- [ ] Implement GMaps module DocumentViewModel class.
