### ISSUE TITLE
Add SharpMap Plugin

### ISSUE THREAD

**Issue by Squill3x** [Squill3x/xsealence#4]
# Feature Request

### Description:
Add SharpMap plugin.

### Tasks:
- [x] Add SharpMap plugin module.
- [x] Implement SharpMap module GISEngineBase class.
- [x] Implement SharpMap module DocumentViewModel class.
