### ISSUE TITLE
Add MapWinGIS Plugin

### ISSUE THREAD

**Issue by Squill3x** [Squill3x/xsealence#5]
# Feature Request

### Description:
Add MapWinGIS plugin.

### Tasks:
- [ ] Add MapWinGIS plugin module.
- [ ] Implement MapWinGIS module GISEngineBase class.
- [ ] Implement MapWinGIS module DocumentViewModel class.
