### ISSUE TITLE
Create Toolbox View

### ISSUE THREAD

**Issue by Squill3x** [Squill3x/xsealence#8]
# Feature Request

### Description:
Create a toolbox view in the DockingManager containing tools used to operate on the currently displayed map.

### Tasks:
- [x] Create toolbox view
- [x] Implement method to load tools from plugins
- [x] Have toolbox view keep track of active plugin view
